author: Suguru Kishimoto
author_url: https://github.com/sgr-ksmt
github_url: https://github.com/sgr-ksmt/Lobster
module: Lobster
readme: README.md
exclude:
  - Sources/UIColor+Ex.swift
output: docs
theme: fullwidth
clean: true
skip_undocumented: true
min_acl: public
xcodebuild_arguments:
  - -sdk
  - iphonesimulator
  - -scheme
  - Lobster
  - -workspace
  - Lobster.xcworkspace
# custom_categories:
#  - name: _
#    children:
#    - _